name: Dopamine_Booster
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  external_app_launcher: ^4.0.1
  firebase_core: ^3.8.1
  fl_chart: ^0.63.0
  http: ^1.0.0
  path_provider: ^2.0.13
  open_file_plus: ^3.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  url_launcher: ^6.1.20
  equatable: ^2.0.5
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  google_fonts: 5.1.0
  flutter_localization: ^0.2.2
  toggle_switch: ^2.3.0
  intl: any  
  flutter_localizations:
    sdk: flutter

  # User repository as a local package
  user_repository:
    path: packages/user_repository
  quiz_repository:
    path: packages/quiz_repository
  


dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_android: true


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
  generate: true
  
  assets:
      - assets/images/
      - assets/avatars/
      - assets/categories/
      - assets/categories/default_category.png
      - assets/app_icon.png
      - assets/flags/usa_flag.png
      - assets/flags/il_flag.png